name: Executar Script Python Periodicamente

on:
  schedule:
    - cron: "*/01 * * * *"  # Executa a cada hora (veja mais exemplos abaixo)
  workflow_dispatch: # Permite execução manual

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Criar credentials.json
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credencial_google.json        

      - name: Executar o script
        run: python atualizar_fatura_easy_ocr.p